apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.157
  selector:
    app: ftps
  ports:
  - port: 21
    name: ftps-control
    targetPort: 21
    protocol: TCP
  - port: 20
    name: ftps-data
    targetPort: 20
    protocol: TCP
  - port: 21000
    name: ftps-passw
    targetPort: 21000
    protocol: TCP


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: service_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 20
